
- name: install redis files
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: installed
    disable_gpg_check: true


- name: dnf module enable
  ansible.builtin.shell: dnf module enable redis:remi-6.2 -y

- name: install redis server
  ansible.builtin.yum:
    name: redis
    state: installed


- name: update the redis listen address
  ansible.builtin.replace:
    path: "{{item}}"
    regexp: 127.0.0.1
    replace: 0.0.0.0
  loop:
    - /etc/redis.conf
    - /etc/redis/redis.conf

- name: start redis service
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes