
- name: copy the mongodb repo files
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo


- name: install mongodb
  ansible.builtin.yum:
    name: mongodb-org
    state: installed


- name: start mongodb service
  ansible.builtin.systemd:
    name: mongosh
    state: restarted
    enabled: yes