- name: crete parameters
  hosts: localhost
  connection: local
  tasks:
    - name: Create parameter
      community.aws.aws_ssm_parameter_store:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        region: us-east-1
      loop:
        - {name: "dev.cart.REDIS_HOST", value: "redis-dev.devops70roboshop.online" }
        - {name: "dev.cart.CATALOGUE_HOST", value: "catalogue-dev.devops70roboshop.online" }
        - {name: "dev.catalogue.MONGO", value: "true" }
        - {name: "dev.catalogue.MONGO_URL", value: "mongodb://mongodb-dev.devops70roboshop.online:27017/catalogue" }
        - {name: "dev.frontend.CATALOGUE_URL", value: "http://catalogue-dev.devops70roboshop.online:8080/" }
        - {name: "dev.frontend.USER_URL", value: "http://user-dev.devops70roboshop.online:8080/" }
        - {name: "dev.frontend.CART_URL", value: "http://cart-dev.devops70roboshop.online:8080/" }
        - {name: "dev.frontend.SHIPPING_URL", value: "http://shipping-dev.devops70roboshop.online:8080/" }
        - {name: "dev.frontend.PAYMENT_URL", value: " http://payment-dev.devops70roboshop.online:8080/" }

        - {name: "dev.shipping.CART_ENDPOINT", value: "cart-dev.devops70roboshop.online:8080" }
        - {name: "dev.shipping.DB_HOST", value: "mysql-dev.devops70roboshop.online" }
        - {name: "dev.user.MONGO", value: "true" }
        - {name: "dev.user.REDIS_HOST", value: "redis-dev.devops70roboshop.online" }
        - {name: "dev.user.MONGO_URL", value: "mongodb://mongodb-dev.devops70roboshop.online:27017/catalogue" }
        - {name: "dev.payment.CART_HOST", value: "cart-dev.devops70roboshop.online" }
        - {name: "dev.payment.USER_HOST", value: "user-dev.devops70roboshop.online" }
        - {name: "dev.payment.CART_PORT", value: "8080" }
        - {name: "dev.payment.USER_PORT", value: "8080" }
        - {name: "dev.payment.AMQP_HOST", value: "rabbitmq-dev.devops70roboshop.online" }
        - {name: "dev.payment.AMQP_USER", value: "roboshop" }


   # PASSWORDS SHOULD NEVER KEPT UNDER THIS REPOS PASSWORD SHOULD BE CREATED MANUALLY.. FOR LAB PRACTICE ONLY DOING

    - name: Create  secret parameter
      community.aws.aws_ssm_parameter_store:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        region: us-east-1
        string_type: "SecureString"
      loop:
        - {name: "dev.payment.AMQP_PASS", value: "roboshop123" }
        - {name: "dev.rabbitmq.AMQP_PASS", value: "roboshop123" }
        - {name: "dev.mysql.DB_ADMIN_USER", value: "root" }
        - {name: "dev.MYSQL.DB_ADMIN_PASS", value: "RoboShop@1" }