#
#print_head "install Phython"
#yum install python36 gcc python3-devel -y &>>${log}
#status_check
#
#APPPRERQ
#
#print_head "download the dependency"
#cd /app
#pip3.6 install -r requirements.txt   &>>${log}
#status_check
#
#print_head "UPDATE PASSWORD IN SERVICE FILE"
#sed -i -e 's/roboshop_rabbitmq_password/${roboshop_rabbitmq_password}/' ${script_location}/files/${component}.service &>>${log}
#status_check
#
#systemD_set

- name: install python
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: app prereq files import
  ansible.builtin.include_tasks: "app-prereq.yml"


- name: download dependencies
  ansible.builtin.pip:
    requirements: /app/requirement.txt
    executable: pip3.6

- name: systemd set up
  ansible.builtin.include_tasks: "systemd.yml"

- name: load schema
  ansible.builtin.include_tasks: "{{schema_type}}-schema.yml"
  when: schema_load

