

- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: remove a directory
  ansible.builtin.file:
    path: /app
    state: absent


- name: ctreate html  directory
  ansible.builtin.file:
    path: /app
    state: directory


- name: download frontend app content
  ansible.builtin.unarchive:
    src: http://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /app
    remote_src: yes

- name: copy the roboshop config file to nginx
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: start nginx service
  ansible.builtin.systemd:
    state: restarted
    name: nginx
    enabled: yes
