
- name: configure the erlang and rabitmq files
  ansible.builtin.shell: curls -s {{ item }} |  bash
  loop:
    - https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh
    - https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh

- name: install erlang and rabbitmq server
  ansible.builtin.yum:
    name:
      - erlang
      - rabbitmq-server
    state: installed

- name: start rabbitmq server
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: restarted
    enabled: yes


- name: Add application user
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: "{{roboshop_rabbitmq_password}}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
    tags: administrator