
- name: diable mysql 8 version
  ansible.builtin.shell: dnf module disable mysql -y

- name: copy mysql repo files
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: install mysql server
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed

- name: start mysqld
  ansible.builtin.systemd:
    name: mysqld
    state: restarted
    enabled: yes

- name: reset dafault database password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{root_mysql_password}}

