- name: copy the mongodb repo files
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo


- name: install mongodb
  ansible.builtin.yum:
    name: mongodb-mongosh
    state: installed


- name: load schema
  community.mongodb.mongodb_shell:
    login_host: mongodb-dev.devops70roboshop.online
    file: "/app/schema/{{component}}.js"
    idempotent: yes
