- name: copy the mongodb repo files
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo


- name: install mongodb server
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

# mongodb-mongosh
#- name: load schema
#  community.mongodb.mongodb_shell:
#    login_host: mongodb-dev.devops70roboshop.online
#    file: "/app/schema/{{component}}.js"
#    idempotent: yes

- name: load schema
  ansible.builtin.shell: mongo --ssl --host dev-docdb-cluster.cluster-crle4cpexxvd.us-east-1.docdb.amazonaws.com:27017 --sslCAFile /app/rds-combined-ca-bundle.pem --username {{ lookup('aws_ssm', "{{env}}.docdb.DB_ADMIN_USER", region='us-east-1' ) }} --password {{ lookup('aws_ssm', "{{env}}.docdb.DB_ADMIN_PASS", region='us-east-1' ) }}