- name: configure nodejs.yml repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: install nodejs.yml
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: add application user
  ansible.builtin.user:
    name: roboshop

- name: remove old app content
  ansible.builtin.file:
    path: /app
    state: absent

- name: create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: download the {{component}} zip  content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: /app
    remote_src: yes

- name: install nodejs.yml dependencies
  community.general.npm:
    path: /app
    state: latest

- name: copy systemd file
  ansible.builtin.copy:
    src: "{{component}}.service"
    dest: /etc/systemd/system/{{component}}.service

- name: start catalogue service
  ansible.builtin.systemd:
    name: "{{component}}"
    daemon_reload: yes
    enabled: yes
    state: restarted

- name: copy the mongodb repo files
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo


- name: install mongodb
  ansible.builtin.yum:
    name: mongodb-mongosh
    state: installed


- name: load schema
  community.mongodb.mongodb_shell:
    login_host: mongodb-dev.devops70roboshop.online
    file: "/app/schema/{{component}}.js"
    idempotent: yes